### ISSUE TITLE
./configure breaks on OS X because libtoolize is named glibtoolize

### ISSUE THREAD

**Issue by specious** [btrask/stronglink#101]
Even though I've got homebrew package `libtool` installed, `./configure` fails when running `deps/snappy/autogen.sh` because it doesn't check if the platform is Darwin and call `glibtoolize` instead of `libtoolize`:

```
﻿﻿$ ./configure
 ...
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating include/openssl/Makefile
config.status: creating crypto/Makefile
config.status: creating ssl/Makefile
config.status: creating tls/Makefile
config.status: creating tests/Makefile
config.status: creating apps/Makefile
config.status: creating apps/openssl/Makefile
config.status: creating apps/nc/Makefile
config.status: creating man/Makefile
config.status: creating libcrypto.pc
config.status: creating libssl.pc
config.status: creating libtls.pc
config.status: creating openssl.pc
config.status: executing depfiles commands
config.status: executing libtool commands
./autogen.sh: line 5: libtoolize: command not found
```

The [libtool install script](https://github.com/Homebrew/homebrew/blob/8452ef17be1d7a41d13cedf5328ecf9fb0de325c/Library/Formula/libtool.rb#L32) warns that:

```rb
 def caveats; <<-EOS.undent
   In order to prevent conflicts with Apple's own libtool we have prepended a "g"
   so, you have instead: glibtool and glibtoolize.
   EOS
 end
```

This [suggestion](http://stackoverflow.com/a/15448876/1289901) on stackoverflow is to check `uname` and call libtoolize accordingly.  There is a (currently somewhat questionable) [pull request](https://github.com/google/snappy/pull/4) open upstream.

**Comment by specious** [comment]
The snappy.rb formula in homebrew [solves this](https://github.com/Homebrew/homebrew/blob/29c40fa3d94929b0d62986a1ed0fbdae97228512/Library/Formula/snappy.rb#L32) by replacing `libtoolize` with `glibtoolize` before running `autogen.sh`:

```rb
if build.head?
  # https://github.com/google/snappy/pull/4
  inreplace "autogen.sh", "libtoolize", "glibtoolize"
  system "./autogen.sh"
end
```

**Comment by btrask** [comment]
Thanks @specious! Hopefully fixed in 51ba2aa8cb5fef4fdb99f2db535210270b64cc80. Please let me know if it works.

**Comment by specious** [comment]
Success:v:

**Comment by btrask** [comment]
Great, thanks!

**Comment by btrask** [comment]
BTW, do you have a list of Homebrew dependencies?

**Comment by specious** [comment]
Hold on, I'm compiling...

![stronglink-compiling](https://cloud.githubusercontent.com/assets/451178/11710348/7b12ea10-9eec-11e5-8266-f5a46217d097.png)
