### ISSUE TITLE
Lynx support and "Connection: close"

### ISSUE THREAD

**Issue by btrask** [btrask/stronglink#103]
@specious reported that Lynx would hang when visiting a StrongLink site. We were too lazy to handle `Connection: close`, and it was waiting for the connection to end.

**Comment by btrask** [comment]
Fixed in b79d9cf31672615dfc79ad4081e5b951c73e2e68. Lynx works great!

**Comment by specious** [comment]
Boomshaka!

By the way, [links](http://links.twibright.com/) and [elinks](http://elinks.or.cz/) weren't showing this symptom.  Perhaps we can mention something about resiliency on the [lynx-dev mailing list](http://lists.nongnu.org/archive/html/lynx-dev/).
