### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by akkartik** [btrask/stronglink#89]
```bash
$ ./configure
sh: VERSION: No such file or directory
sh: crypto/VERSION: No such file or directory
sh: ssl/VERSION: No such file or directory
sh: tls/VERSION: No such file or directory
configure.ac:21: error: AC_INIT should be called with package and version arguments
/usr/share/aclocal-1.14/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:21: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
```

Tracing the scripts it seems to be caused by the `autoreconf -i -f` in deps/libressl-portable. Am I missing some dependency? I ran this as directed:

```
$ sudo apt-get install gcc g++ gobjc cmake automake autoconf libtool pkg-config
```

**Comment by btrask** [comment]
Sorry, this is a bug in the configure script. You need to run ./update.sh in the deps/libressl-portable dir first. I'll put together a change ASAP.

**Comment by btrask** [comment]
For now I've just added it to the "Basic Installation" steps in INSTALL.md. I'll open an issue for making LibreSSL setup easier.

**Comment by btrask** [comment]
Let me know if you can get it working now.

**Comment by akkartik** [comment]
Yep, it compiled! Now when I try to run it I see this error:

```
Blog couldn't load template at .../blog/template/header.html
Blog server could not be initialized

Stopping StrongLink server...
```

The directory I gave it is just empty. Is it expecting some specific structure? Is it because I tried to run it directly from the `build` directory? (`make install`.. I'm not ready for that kind of commitment :) )

**Comment by btrask** [comment]
By default it tries to load templates from the installed path. What you can do instead is symlink (or copy) the res/blog directory into the repo directory that you're using.

Sorry for the problems, I'll add this to the install notes too!

**Comment by akkartik** [comment]
Thanks! I actually went searching for `header.html`, but only inside build, I think.. Anyway, that got me past that hurdle. Now I get this:

```
TLS config error: failed to load certificate file
```

Any hints? I've never actually successfully setup SSL before..

**Comment by btrask** [comment]
If you want to run without TLS, you need to set the `SERVER_PORT_TLS` to NULL in `src/blog/main.c`.

I hope this is the last hurdle, I can't think of any others.

**Comment by akkartik** [comment]
It's up!

![screenshot from 2015-09-03 15 45 18](https://cloud.githubusercontent.com/assets/3161/9672834/e194ed56-5252-11e5-8fbe-38a7a3be8026.png)

That wasn't too bad at all :) I think you're too apologetic in your install instructions. Tell people they need to man up and build from source :D

**Comment by btrask** [comment]
Great! Thanks for being so patient and helping me discover a lot of first-run problems.

I'm apologetic because most people won't go through 1% of what you did. But the project is still young...

**Comment by akkartik** [comment]
I have enough experience with my own projects to absolutely understand.

**Comment by btrask** [comment]
Can I ask what your interest is in StrongLink, what you'd like to get out of it or what you're looking for? And any other feedback you may have.

**Comment by akkartik** [comment]
It was a combination of:

a) reading your [substance guide](https://github.com/btrask/stronglink/blob/6f8d9016b8/SUBSTANCE.md) and wanting to look at the code that led to it, that came out of a seemingly like-minded belief system (http://akkartik.name/post/readable-bad). I like looking at other people's code (the kind that has been lovingly cultivated), and it's a long-standing frustration that it's never as easy as it should be, no matter how hard the author tries: http://akkartik.name/about

b) reading your [https://bentrask.com/notes/content-addressing.html](principles of content addressing) and wanting to see what a platform that meets it feels like. I have my own private note-taking system (evolved out of a single notes file, now in version control, sends 1% of items tagged 'publish' to my site/blog) so I'm interested in this space (wiki notebooks, federated wikis, delicious folksonomies, etc.) and am constantly on the lookout for ideas to steal.

While I was trying to get it running I somehow failed to notice that it powers your blog. Are most of your notes hosted by Stronglink publicly accessible, or is it 1% tip-of-the-iceberg, 99% dark-matter like my system?

**Comment by akkartik** [comment]
Ah, I now see [https://bentrask.com/?q=hash%3A%2F%2Fsha256%2F88d9e8eb7df18460da8d0c3996881f3a1c7fc95ab8e5c6ea9e250c8c49bc0910](this post of yours) which partially answers my question.

**Comment by akkartik** [comment]
Reminds me of [this ancient thing I built](http://blog.hystry.com/post/2834769/welcome-to-hystry).

**Comment by btrask** [comment]
Wow, great stuff. I will read through everything you posted.

Of my notes about 1500 are public and 7000 are private. So it's a lot more than 1% but still a small fraction. I want to publish more of them over time but it's a lot of effort just going through them.

I tend to write about everything, so I will probably do a blog post on this discussion tonight/tomorrow. I will put full stats in there too (and explain the `sln-stats` tool that anyone can run).

**Comment by akkartik** [comment]
I sent you an email. Let me know if you'd prefer to continue here or elsewhere.

**Comment by btrask** [comment]
I believe bug trackers should be considered the "user interface" of a software project, so I don't mind talking here to keep the conversation public if you want. And by all means please send me all your comments until you get bored!

**Comment by btrask** [comment]
BTW I don't have internet at home, so I basically only get online once a day (at most). That is why my responses are sometimes delayed.

**Comment by btrask** [comment]
https://bentrask.com/?q=hash://sha256/5feb5bb05d8295525286098d60551c40487141dde9e71599430339f4124a8a32
https://bentrask.com/?q=hash://sha256/304bfda69f145fd722f7a836d1a86dbe77731e21ed699bf0033c632a7e3e468c
